/*
** File:    UXFCR.h
**
** Author:  Ron Hayter
** Date:    93-12-13
**
** Purpose: An export format DLL for reports.
**
** Copyright (c) 1993  Crystal Services
*/

#if !defined (UXFCR_H)
#define UXFCR_H

//#include "UXDLL.h"
//#include "UXFormat.h"

#if defined (__cplusplus)
extern "C"
{
#endif

#define UXFCrystalReportType    0

// No options.

#if defined (__cplusplus)
}
#endif

#endif // UXFCR_H
