/*
** File:    UXFDoc.h
**
** Author:  Douglas Lankshear
** Date:    93-07-08
**
** Purpose: An export format DLL for Doc files.
**
** Copyright (c) 1993  Crystal Services
*/

#if !defined (UXFDOC_H)
#define UXFDOC_H

//#include "UXDLL.h"
//#include "UXFormat.h"

#if defined (__cplusplus)
extern "C"
{
#endif

#define UXFWordWinType          0
#define UXFWordDosType          1
#define UXFWordPerfectType      2

// No options.

#if defined (__cplusplus)
}
#endif

#endif // UXFDOC_H
