/*
** File:    UXFRTF.h
**
** Author:  Douglas Lankshear
** Date:    93-07-08
**
** Purpose: An export format DLL for Doc files.
**
** Copyright (c) 1993  Crystal Services
*/

#if !defined (UXFRTF_H)
#define UXFRTF_H

//#include "UXDLL.h"
//#include "UXFormat.h"

#if defined (__cplusplus)
extern "C"
{
#endif

#define UXFRichTextFormatType  0

// No options.

#if defined (__cplusplus)
}
#endif

#endif // UXFRTF_H
