/*
** File:    UXFText.h
**
** Author:  Ron Hayter
** Date:    93-05-31
**
** Purpose: An export format DLL for text.
**
** Copyright (c) 1993  Crystal Services
*/

#if !defined (UXFTEXT_H)
#define UXFTEXT_H

//#include "UXDLL.h"
//#include "UXFormat.h"

#if defined (__cplusplus)
extern "C"
{
#endif

#define UXFTextType             0
#define UXFTabbedTextType       1

// No options.

#if defined (__cplusplus)
}
#endif

#endif // UXFTEXT_H
