/*
** File:    UXFWks.h
**
** Author:  Douglas Lankshear
** Date:    93-06-29
**
** Purpose: An export format DLL for Lotus Wks.
**
** Copyright (c) 1993  Crystal Services
*/

#if !defined (UXFWKS_H)
#define UXFWKS_H

//#include "UXDLL.h"
//#include "UXFormat.h"

#if defined (__cplusplus)
extern "C"
{
#endif

#define UXFLotusWksType    0
#define UXFLotusWk1Type    1
#define UXFLotusWk3Type    2

// No options.

#if defined (__cplusplus)
}
#endif

#endif // UXFWKS_H
