/*
** File:    UXFXls.h
**
** Author:  Douglas Lankshear
** Date:    93-07-08
**
** Purpose: An export format DLL for Excel Xls.
**
** Copyright (c) 1993  Crystal Services
*/

#if !defined (UXFXLS_H)
#define UXFXLS_H

//#include "UXDLL.h"
//#include "UXFormat.h"

#if defined (__cplusplus)
extern "C"
{
#endif

#define UXFXls2Type    0
#define UXFXls3Type    1
#define UXFXls4Type    2

// No options.

#if defined (__cplusplus)
}
#endif

#endif // UXFXLS_H
