//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CPECALLS.RC
//
#define IDR_MAINFRAME                   2
#define IDR_MAINFRAME2                  2
#define IDD_ABOUTBOX                    100
#define IDI_ICON2                       103
#define Formula_Box                     104
#define IDD_DIALOG1                     105
#define IDD_Report_Formulas             105
#define IDD_Server                      106
#define IDD_Table_Location              107
#define IDD_Sql_Query                   112
#define IDD_Selection_Formulas          113
#define IDD_Access_Security             115
#define IDD_Stored_Procedures           117
#define IDD_Group_Selection_Formula     118
#define IDD_Report_Title                119
#define IDD_Graph_Main                  120
#define IDD_Graph_Type                  121
#define IDD_Graph_Text                  122
#define IDD_Application_Architecture    123
#define Formula_Name                    1000
#define Formula_text                    1001
#define IDGet                           1002
#define IDSET                           1003
#define IDC_Set                         1004
#define IDC_Get                         1005
#define IDC_Formula_Text                1007
#define IDC_Check_Formula               1008
#define IDC_Get_Info_Button             1009
#define IDC_Set_Info_Button             1010
#define IDC_Clear_setting_Button        1011
#define IDC_Server_Name                 1012
#define IDC_Database_Name               1013
#define IDC_User_ID                     1014
#define IDC_Password                    1015
#define IDC_Table_Combo                 1016
#define IDC_set_location                1017
#define IDC_Table_Location              1018
#define IDC_Dll_Name                    1019
#define IDC_Descriptive_Name            1020
#define IDC_Database_Type               1021
#define IDC_Get_SQL                     1023
#define IDC_Set_SQL                     1024
#define IDC_SQL_Text                    1025
#define IDC_SQL_Info                    1026
#define IDC_Set_Selection_Formula       1027
#define IDC_Get_Selection_Button        1028
#define IDC_Selection_Text              1029
#define IDC_Set_Security                1030
#define IDC_Get_Security                1031
#define IDC_UserID_Text                 1032
#define IDC_Password_Text               1033
#define IDC_Formula_Combo               1034
#define IDC_Parameter_Combo             1035
#define IDC_Parameter_Text              1036
#define IDC_Set_Parameter               1037
#define IDC_Set_Group_Formula           1038
#define IDC_Get_Group_Formula           1039
#define IDC_Title_Text                  1041
#define IDC_Set_Title                   1042
#define IDC_Type                        1043
#define IDC_Text                        1044
#define IDC_Format                      1045
#define IDC_Number_Combo                1046
#define IDC_Section_Combo               1047
#define IDC_Type_Combo                  1048
#define IDC_SubTitle_Text               1051
#define IDC_FootNote_Text               1052
#define IDC_Group_Text                  1053
#define IDC_Series_Text                 1054
#define IDC_XAxis_Text                  1055
#define IDC_YAxis_Text                  1056
#define IDC_ZAxis_Text                  1057
#define IDC_App_Text2                   1061
#define IDC_Text3                       1062
#define IDC_Text4                       1063
#define ID_FILE_OPENENGINE              32771
#define ID_FILE_CLOSEENGINE             32772
#define ID_JOB_OPENPRINTJOB             32773
#define ID_JOB_CLOSEPRINTJOB            32774
#define ID_JOB_STARTPRINTJOB            32775
#define ID_DESTINATION_OUTPUTTOWINDOW   32776
#define ID_DESTINATION_OUTPUTTOPRINTER  32777
#define ID_OPTIONS_FORMULAS             32778
#define ID_OPTIONS_SETSELECTIONFORMULA  32781
#define ID_OPTIONS_SETFORMULATEST_TESTAVGOFLASTYRSALES 32784
#define ID_OPTIONS_SETFORMULA_TESTLASTYRSALES1000 32785
#define ID_OPTIONS_GETSELECTIONFORMULA  32786
#define ID_OPTIONS_INVOKEFORMULABOX     32787
#define ID_DESTINATION_OUTPUTTOFILEEXPORT 32788
#define ID_ENGINE_LOGONSERVER           32789
#define ID_OPTIONS_GETSETSQLQUERY       32790
#define ID_OPTIONS_GETSETSELECTIONFORMULA 32791
#define ID_OPTIONS_TABLELOCATION        32792
#define ID_ENGINE_ACCESSSECURITY        32793
#define ID_OPTIONS_STOREDPROCEDURES     32794
#define ID_OPTIONS_GROUPSELECTIONFORMULA 32795
#define ID_FORMAT_REPORTTITLE           32797
#define ID_FORMAT_GRAPHING              32800
#define ID_HELP_APPLICATIONARCHITECTURE 32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
