//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MYCALL.rc
//
#define ID_OPENREPORT                   0
#define IDD_ABOUTBOX                    100
#define ID_OPENRPT                      101
#define IDD_SELECTEVENTS                102
#define IDS_FILETYPE                    103
#define IDS_FILEFILTER                  104
#define ID_STATUSBARUPDATE              105
#define ID_OPENJOB                      106
#define ID_START                        107
#define ID_CLOSEPRINTJOB                108
#define IDC_MAINLIST                    109
#define ID_MAINFORM                     110
#define IDD_WINDOWOPTIONS               111
#define ID_CLEARWINDOW                  112
#define ID_Logon                        113
#define ID_LOGONTABLE                   114
#define ID_LOGONSERVER                  115
#define ID_DISCARDSAVEDDATA             116
#define IDS_LOGFILTER                   117
#define IDS_LOGTYPE                     118
#define IDC_FILELOCATION                119
#define IDC_TESTLOGON                   120
#define IDD_CURSORBAR                   121
#define IDR_MAINFRAME                   128
#define IDC_AREA                        128
#define IDR_MYCALLTYPE                  129
#define IDC_CURSORTYPE                  129
#define IDC_SETCURSOR                   130
#define IDD_LOGONSERVER                 132
#define IDD_TABLELOGON                  133
#define IDC_EDIT1                       1000
#define IDC_CHECK1                      1001
#define IDC_EDIT2                       1001
#define IDLOGONSERVER                   1003
#define IDC_EDIT3                       1005
#define IDC_EDIT4                       1006
#define IDC_EDIT5                       1007
#define IDC_Tables                      1008
#define IDC_CHECK9                      1009
#define ID_SETLOGON                     1009
#define IDC_CHECK10                     1010
#define IDC_TABLE                       1010
#define IDC_PROPAGATE                   1011
#define IDC_CHECK12                     1012
#define IDC_CHECK13                     1013
#define IDC_CHECK14                     1014
#define IDC_CHECK15                     1015
#define IDC_CHECK16                     1016
#define IDC_TEST                        1016
#define IDC_LIST1                       1019
#define IDC_CHECK2                      1020
#define IDC_CHECK3                      1021
#define IDC_CHECK4                      1022
#define IDC_CHECK6                      1024
#define IDC_CHECK7                      1025
#define IDC_CHECK8                      1026
#define IDC_CHECK11                     1027
#define ID_FILE_CLOSEPRINTJOB           32771
#define ID_FILE_DISCARDSAVEDDATA        32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           131
#endif
#endif
