'
' File:    crwdefs.inc
'
' Author:  Greg Hoffenbacker
' Date:    06 Oct 93
'
' Purpose: Include file for crwsetup.inc, contains defines for different software builds.
'
' Revisions:
'
' Note: Comments begin with ' or REM.  Metacommands begin with '$.
'



' Uncomment the correct define for each different installation.

''$DEFINE CRW
'$DEFINE CRWPRO
''$DEFINE OEM1
''$DEFINE REGISTER_MS_EXCHANGE_CLIENT
'$DEFINE REGISTER_OCX
''$DEFINE ASSOCIATE_CVW
'$DEFINE NO_SVR_CONF

