//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by peclass.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_SELFORMULA                  130
#define IDD_DIALOG1                     131
#define IDD_LOGONSERVER                 132
#define IDI_ICON1                       132
#define IDD_TABLELOGON                  133
#define IDD_SETFORMULA                  134
#define IDD_SQLQUERY                    135
#define IDI_CRW_ICON                    144
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDSet                           1002
#define IDLOGONSERVER                   1003
#define IDC_EDIT3                       1005
#define IDC_EDIT4                       1006
#define IDC_EDIT5                       1007
#define IDC_COMBO1                      1008
#define IDC_Tables                      1008
#define IDC_CFNAME                      1008
#define ID_SETLOGON                     1009
#define IDC_TABLE                       1010
#define IDC_PROPAGATE                   1011
#define IDC_NEWSELECTFORMULA            1012
#define IDC_OK                          1013
#define IDC_SET                         1014
#define IDC_FORMTEXT                    1015
#define IDC_TEST                        1016
#define IDC_SQLTEXT                     1017
#define ID_FILE_PRINT_WINDOW            32771
#define ID_FILE_PRINT_PRINTER           32772
#define ID_FILE_PRINT_EXPORT            32773
#define ID_REPORT_PREVIEW               32777
#define ID_REPORT_TOPRINTER             32778
#define ID_REPORT_EXPORT                32779
#define ID_FORMULA_SETFORMULAE          32780
#define ID_FORMULA_SETFORMULA           32780
#define ID_FORMULA_SETSELECTIONFORMULA  32781
#define ID_LOGON_LOGONSQLSERVER         32782
#define ID_LOGON_TABLELOGONINFO         32783
#define ID_SQL_STOREDPROCEDURE          32784
#define ID_SQLQUERY                     32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
